Portafolio set up
Dachrono/Portfolio-setup-and-mobile-first pull request #1
Opened 2023-04-27 20:37 UTC by Dachrono

2023-04-27 21:42 UTC, Dachrono commented
- Install the linters and check the correct function
- Added the html file and created the page
- Added the css and created the code to fix visual html 
- Added readme and created the infomation about it 
- Added the license and images to readme, tst.md

2023-04-27 22:52 UTC, abdulhamiid requested changes
# Status: Required Changes :recycle:
Hi @Dachrono 👋, 
![Alt Text](https://c.tenor.com/vOLW_UQMySIAAAAC/almost-there.gif)
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights 🌟

- ✔️ Descriptions are very descriptive
- ✔️ Linters checks are passing
- ✔️ Use GitHub Flow
- ✔️ Meaningful commit messages.

## Required Changes ♻️
_Please kindly check the comments under the review._

## Optional suggestions 🤷‍♂️
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-27 22:52 UTC, abdulhamiid commented on index.html
> +            <a href="" class="icon"><i class="fa fa-bars"></i></a>
![image](https://user-images.githubusercontent.com/78251927/235002465-6e507d30-9e85-4172-9c3b-6d7d0a4f6c4a.png)

Kindly wrap the `Hamburger` button inside the `nav` tag, the `nav` tag is for semantics reasons. 🛠👍

2023-04-27 22:52 UTC, abdulhamiid commented on index.html
> +    </div>
Kindly make the container of the section a `section` tag.
* It represents a generic standalone section of the document, let's use it 🤗. [Check this link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section) for more info.. 🛠💪


Kindly use the section `background` and `font` defined for the template so that our design looks like the template as much as possible according to the [project requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/1_setup.md).

Your Design
![image](https://user-images.githubusercontent.com/78251927/235006079-9b8d7d5c-104e-4878-b093-462fa39f67a6.png)

Figma
![image](https://user-images.githubusercontent.com/78251927/235005997-970877dc-18d1-4d39-be34-c69f76317062.png)

2023-04-27 22:52 UTC, abdulhamiid commented on index.html
> +            <p id="a">Hey there. I’m Andy.</p>
Kindly make the main title `Hey there ...` an `h1` tag.

* If we want that google (and other search engines) to know about a specific topic, we use an `h1` tag. [Check this link](https://www.reliablesoft.net/h1-tag/) for more info. 🛠👍

2023-04-27 22:52 UTC, abdulhamiid commented on index.html
> +            <p id="c">
Kindly consider using `hx` (examples: `<h1>`,`<h2>`,`<h3>`, etc...) for the subtitle subtitle `I'm a software developer`. 🤗

Preferably an `h2` tag, Semantically, it's good to use the common order with the tags h1 - h6.

So after `h1` it's preferred to use `h2` next 💪🤗

2023-04-27 22:52 UTC, abdulhamiid commented on index.html
> +        </div>
According to the [project requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/1_setup.md), let's use a `ul` tag to group the list of icons, and `li` per icon; each icon has a link (`a` tag). 🛠

* Apart from being semantically correct, the `a` tag will let you connect your social networks with the icons, using `href`. 🛠💪

2023-04-28 16:47 UTC, Dachrono commented on index.html
> +    </div>
![image](https://user-images.githubusercontent.com/119348116/235202291-418aef3b-40f6-42e8-87cd-61d2abf1dcf6.png)
the back ground now its ok, you can check it with the movile resolution

and I find the font and it is ready 

I solved the sections too

2023-04-28 16:50 UTC, Dachrono commented on index.html
> +            <p id="a">Hey there. I’m Andy.</p>
solved

2023-04-28 16:52 UTC, Dachrono commented on index.html
> +            <p id="c">
solved

2023-04-28 17:16 UTC, Dachrono commented on index.html
> +        </div>
solved

2023-04-28 17:27 UTC, Dachrono commented
- hamburger menu correction
- sections correction
- fonts and background corrections
- tags hx correcctions
- solve the ul and li whit a tag
- solve some issues whit the semantic in css
@abdulhamiid

2023-04-28 18:04 UTC, ABDULALI3468 requested changes
# Changes Required 👍 

Hi @Dachrono , 

<img src="https://media1.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif"/>

Great work on making the changes requested by a previous reviewer 👏 
You've done really well implementing some of the requested changes, but there are still some which aren't been addressed yet.


## Highlights
✅All linters are checked.
✅Project is professionally documented.
✅The right GitHub flow method has been used.
✅Professional pull request title and description.


 ## Required Changes ♻️

> **_Check the comments below to have a look at the required changes._**

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification.

> * This is My **GitHub**: ![GitHub followers](https://img.shields.io/github/followers/ABDULALI3468?label=ABDULALI&style=social)
> * This is My **Linkedin**: [![Linkedin Badge](https://img.shields.io/badge/-ABDUL%20ALI-blue?style=flat-square&logo=Linkedin&logoColor=white&link=https://www.linkedin.com/in/abdul-ali-5400bb216/)](https://www.linkedin.com/in/abdul-ali-5400bb216/)&nbsp;
> * This is My **Twitter**: [![Twitter Badge](https://img.shields.io/badge/-@mrabdul_ali_-1ca0f1?style=flat-square&labelColor=1ca0f1&logo=twitter&logoColor=white&link=https://twitter.com/mrabdul_ali)](https://twitter.com/mrabdul_ali)&nbsp;

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-28 18:04 UTC, ABDULALI3468 commented on index.html
> +            </h3>
Currently, the styles you used are still not similar to the Figma template please consider reviewing your styles and making necessary changes and before asking for a review match them and ask your self are they the same or not it will help you throughout journey. 

 > One thing different was the `width and line-height properties`


You can add the following properties to the selector to make it closer to the design:-

```
    line-height: 28px;
    width: 327px;
```

2023-04-28 18:04 UTC, ABDULALI3468 commented on index.html
> +<body>
In the styles the background image needs to be exactly starting from the walls of the screen currently there is a default margin that is avoiding it from sticking to the sides of the screen please consider making the margin 0 on the body tag to make it look better and closer to the design.

```
   margin: 0;
```

2023-04-28 18:04 UTC, ABDULALI3468 commented on index.html
> +            </h3>
**[OPTIONAL]** The paragraph needs to be a `p` tag.

* This way will be semantically correct and the screen readers and other technologies will thank you

2023-04-28 18:43 UTC, Dachrono commented on index.html
> +        <section class="title">
solved

2023-04-28 18:43 UTC, Dachrono commented on index.html
> +            </h3>
solved

2023-04-28 18:44 UTC, Dachrono commented on index.html
> +<body>
solved

2023-04-28 18:45 UTC, Dachrono commented on index.html
> +            </h3>
solved

2023-04-28 19:45 UTC, Dachrono commented
-correct container section
-corrected id=c type <p> and style css
-corrected margin body

2023-04-28 20:01 UTC, DuaneDave approved these changes
Hi @Dachrono  👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✔️ All issues has been resolved
✔️ UI is looking smart

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-28 21:05 UTC, merged