Web desing
Dachrono/Portfolio-setup-and-mobile-first pull request #4
Opened 2023-05-04 22:23 UTC by Dachrono

- Media querys for web desing
- Added images for webdesing background
- Flex and grid modifications for web desing
- Tag modifications to make better reviews and code control
- Buttons modifications inside li content
- Little works cards desing modifications
- Styling web desing creations

2023-05-04 23:44 UTC, abdulhamiid requested changes
# Status: Required Changes :recycle:
Hi @Dachrono 👋, 
![](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there! :running_man: :runner: 
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights 🌟

- ✔️ Descriptions are descriptive
- ✔️ Linters checks are passing
- ✔️ Use GitHub Flow
- ✔️ Meaningful commit messages.

## Required Changes ♻️
_Please kindly check the comments under the review._

## Optional suggestions 🤷‍♂️
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-04 23:44 UTC, abdulhamiid commented on index.html
> +                <li>Selenium</li>
Kindly adjust the spacing between the cards so that we stick to the design as much as possible using [the info from the Figma templates](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1)

Part of the learning objective of this activity demonstrate our understanding of how to parse a Figma design to create a UI. 👍

Your design
![image](https://user-images.githubusercontent.com/78251927/236348698-199978f5-0ec6-4fa6-b7a2-a97f73d79ac0.png)

Figma
![image](https://user-images.githubusercontent.com/78251927/236348833-9870b9b7-3aec-465e-b9c1-d59f3f61e56d.png)

2023-05-04 23:44 UTC, abdulhamiid commented on index.html
> +        <h1>My recents works</h1>
Your design
![image](https://user-images.githubusercontent.com/78251927/236350070-bf9bb45d-468e-4d4c-89b8-6f1c0a08b606.png)

Figma
![image](https://user-images.githubusercontent.com/78251927/236349731-761d93c0-0e06-4caa-80ad-dad26c03cbeb.png)

Please kindly adjust the Background image so that all parts of the image displays on the page using [the info from the Figma templates](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1) to replicate the design on Figma as much as possible 🛠

2023-05-04 23:44 UTC, abdulhamiid commented on index.html
> +        <div class="social">
Figma
![image](https://user-images.githubusercontent.com/78251927/236350384-fd7f288f-871a-4e7c-a4b1-da40ec810905.png)

Your design
![image](https://user-images.githubusercontent.com/78251927/236350494-439634be-4eba-4054-a518-35ab906f9cc9.png)

Please kindly add the missing line before the list of social media icons. as shown above to replicate the design as much as possible 🛠💪

2023-05-04 23:44 UTC, abdulhamiid commented on index.html
> +        <h1>My recents works</h1>
Your design
![image](https://user-images.githubusercontent.com/78251927/236351663-dac6f735-4420-4e9a-a840-f31230bb214e.png)

Figma
![image](https://user-images.githubusercontent.com/78251927/236351714-9cafe759-b96f-4cc4-a660-7230e6cee7d8.png)

Please kindly consider reducing the font size of the text `My recent works` to match the template. 💪

2023-05-05 18:26 UTC, Dachrono commented on index.html
> +        <ul class="social">
Solved I adjust the contend and size of letters

2023-05-05 18:35 UTC, Dachrono commented on index.html
> +            <li>HTML</li>
Solved I use a margin and paddig vales, and changed the color font

2023-05-05 18:38 UTC, Dachrono commented on index.html
> +                <li>Selenium</li>
Solved I used a gap sentence to do space

2023-05-05 18:39 UTC, Dachrono commented on index.html
> +        <h1>My recents works</h1>
Solved I adjust the background image

2023-05-05 18:40 UTC, Dachrono commented on index.html
> +        <h1>My recents works</h1>
Solved I adjust the font size

2023-05-05 18:50 UTC, Dachrono commented on index.html
> +        <div class="social">
Solved I use a border to do the missed line

2023-05-05 19:32 UTC, divinecharlotte approved these changes
# Hello @Dachrono    😃 🥳 🎉 🎈 

Great Job 😄 👏 You've done it. Your project is complete!  There is nothing else to say  👍🏻 ✅ 
### To Highlight 💯

- Descriptive pr👍 
- linters are passing 👍 






## Congratulations! 🎉 

<img src="https://media3.giphy.com/media/3KC2jD2QcBOSc/giphy.gif"/>

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-05 19:41 UTC, merged